### ISSUE TITLE
Panic on AWS due to disk being too small

### ISSUE THREAD

**Issue by mbentley** [linuxkit/linuxkit#2387]
**Description**
When running on AWS, if your root disk is too small for the AMI, it will panic:

```
$ linuxkit -v run aws onap-aws
INFO[0003] Created instance i-05d6694501dd5bcd2
INFO[0034] Instance i-05d6694501dd5bcd2 is running
WARN[0034] AWS doesn't stream serial console output.
 Please use the AWS Management Console to obtain this output
 Console ouput will be displayed when the instance has been stopped.
WARN[0034] Waiting for instance to stop...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x564db65dced8]

goroutine 1 [running]:
main.runAWS(0xc420010180, 0x1, 0x1)
        /go/src/github.com/linuxkit/linuxkit/run_aws.go:170 +0xfb8
main.run(0xc420010170, 0x2, 0x2)
        /go/src/github.com/linuxkit/linuxkit/run.go:46 +0x170
main.main()
        /go/src/github.com/linuxkit/linuxkit/main.go:88 +0x2c0
```
**Steps to reproduce the issue:**
Deploy to AWS with a disk smaller than the image.

**Describe the results you received:**
panic

**Describe the results you expected:**
More graceful error

**Additional information you deem important (e.g. issue happens only occasionally):**
```
# moby version
moby version 0.0
commit: c2b081ed8a9f690820cc0c0568238e641848f58f
# linuxkit version
linuxkit version 0.0
commit: bbf87410024706b4a5d20f92dad34d55ab0f4229
```

**Comment by mbentley** [comment]
So this is actually a dupe of https://github.com/linuxkit/linuxkit/issues/2389; there is better info there so I'll close this.
