### ISSUE TITLE
Metadata panics when trying to read cdrom

### ISSUE THREAD

**Issue by voima-eetu** [linuxkit/linuxkit#3562]
**Description**

Metadata panics and quits when trying to read cloud-config from ISO cdrom with error:  
`panic: runtime error: index out of range [0] with length 0`

**Steps to reproduce the issue:**

* Run linuxkit as a guest on libvirt qemu.  
* Create iso with cloud-config on a host machine:  
`mkisofs -output <isoDestination> -volid cidata -joliet -rock <userDataFileName> <metaDataFileName> <networkConfigFileName>`
* Attach iso as a cdrom  
* Run `metadata -v`

**Describe the results you received:**

```
metadata -v
DEBU[0000] cdrom devices to be checked: [/dev/sr0]      
DEBU[0000] block devices found: [/sys/class/block/loop0 /sys/class/block/loop1 /sys/class/block/loop2 /sys/class/block/loop3 /sys/class/block/loop4 /sys/class/block/loop5 /sys/class/block/loop6 /sys/class/block/loop7 /sys/class/block/sr0 /sys/class/block/vda /sys/class/block/vda1] 
DEBU[0000] ignoring loop or ram device: loop0           
DEBU[0000] ignoring loop or ram device: loop1           
DEBU[0000] ignoring loop or ram device: loop2           
DEBU[0000] ignoring loop or ram device: loop3           
DEBU[0000] ignoring loop or ram device: loop4           
DEBU[0000] ignoring loop or ram device: loop5           
DEBU[0000] ignoring loop or ram device: loop6           
DEBU[0000] ignoring loop or ram device: loop7           
DEBU[0000] checking device: /dev/sr0                    
DEBU[0000] initDisk(): start                            
DEBU[0000] initDisk(): block device                     
DEBU[0000] initDisk(): logical block size 2048, physical block size 4096 
DEBU[0000] trying fat32                                 
DEBU[0000] fat32 failed: blocksize for FAT32 must be either 512 bytes or 0, not 2048 
DEBU[0000] trying iso9660 with physical block size 4096 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/linuxkit/linuxkit/pkg/metadata/vendor/github.com/diskfs/go-diskfs/filesystem/iso9660.parseDirEntry(0xa60458, 0x0, 0x0, 0xc0000d8000, 0x1c000, 0x0, 0x0)
        /go/src/github.com/linuxkit/linuxkit/pkg/metadata/vendor/github.com/diskfs/go-diskfs/filesystem/iso9660/directoryentry.go:281 +0x789
github.com/linuxkit/linuxkit/pkg/metadata/vendor/github.com/diskfs/go-diskfs/filesystem/iso9660.Read(0x818500, 0xc00000e048, 0x5c000, 0x0, 0x1000, 0x1, 0x8122e0, 0xc0000450c0)
        /go/src/github.com/linuxkit/linuxkit/pkg/metadata/vendor/github.com/diskfs/go-diskfs/filesystem/iso9660/iso9660.go:223 +0x965
github.com/linuxkit/linuxkit/pkg/metadata/vendor/github.com/diskfs/go-diskfs/disk.(*Disk).GetFilesystem(0xc0000765a0, 0x0, 0x0, 0xc0000765a0, 0x0, 0x0)
        /go/src/github.com/linuxkit/linuxkit/pkg/metadata/vendor/github.com/diskfs/go-diskfs/disk/disk.go:227 +0x241
main.FindCIs(0xc0000481e0, 0x7a75a4, 0x1f)
        /go/src/github.com/linuxkit/linuxkit/pkg/metadata/provider_cdrom.go:85 +0x4a0
main.ListCDROMs(0x750dc0, 0xc00000c2a0, 0x4)
        /go/src/github.com/linuxkit/linuxkit/pkg/metadata/provider_cdrom.go:45 +0xf8
main.main()
        /go/src/github.com/linuxkit/linuxkit/pkg/metadata/main.go:105 +0x1795
```

**Describe the results you expected:**

metadata to be able to read cloud-config from a cdrom  

**Additional information you deem important (e.g. issue happens only occasionally):**

virsh vol-dumpxml:  
```
<volume type='file'>
  <name>name.iso</name>
  <key>redacted.iso</key>
  <source>
  </source>
  <capacity unit='bytes'>376832</capacity>
  <allocation unit='bytes'>376832</allocation>
  <physical unit='bytes'>376832</physical>
  <target>
    <path>redacted.iso</path>
    <format type='iso'/>
    <permissions>
      <mode>0644</mode>
      <owner>1000</owner>
      <group>1001</group>
      <label>system_u:object_r:virt_content_t:s0</label>
    </permissions>
    <timestamps>
      <atime>1602577058.070323377</atime>
      <mtime>1602577043.271064392</mtime>
      <ctime>1602577044.112135943</ctime>
    </timestamps>
  </target>
</volume>
```

virsh dumpxml domain:    
```
...
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='redacted.iso'/>
      <backingStore/>
      <target dev='hdd' bus='ide'/>
      <readonly/>
      <alias name='ide0-1-1'/>
      <address type='drive' controller='0' bus='1' target='0' unit='1'/>
    </disk>
...
```

**Comment by voima-eetu** [comment]
Could it be the `-rock` flag in mkisofs command? No Rock Ridge support?

**Comment by Ramblurr** [comment]
I'm using [k3os](https://github.com/rancher/k3os/) with proxmox and I am seeing this same error. `metadata` fails with this error when attempting to read the proxmox generated cloud config cdrom.

**Comment by dweomer** [comment]
It looks like this is getting a zero byte direentry: https://github.com/diskfs/go-diskfs/blob/master/filesystem/iso9660/directoryentry.go#L279 (is proxmox doing something goofy? can you mount and inspect the cdrom geing generated?)

**Comment by Ramblurr** [comment]
I can mount the cdrom with `mount /dev/cdrom /media` and inspect the contents (user, meta and network data) like normal. It seems ok. 

Is there something specific I can share to assist troubleshooting?

**Comment by Ramblurr** [comment]
@dweomer  Here is the contents:

```console
$ mount /dev/cdrom /media
$ cat /media/user-data
#cloud-config
hostname: testagent
k3os:
  datasource: cdrom
  token: shared
  server_url: https://master0.mgmt.mydomain.com:6443

$ cat network-config 
version: 1
config:
    - type: physical
      name: eth0
      mac_address: '6e:00:2d:2d:04:0c'
      subnets:
      - type: dhcp4
    - type: physical
      name: eth1
      mac_address: 'ce:ca:69:1f:3e:81'
      subnets:
      - type: dhcp4
    - type: nameserver
      address:
      - '192.168.1.3'
      search:
      - 'int.mydomain.com'
$ cat meta-data 
instance-id: 7443551de4a80bfc092386c47f127e61864852ae
```

**Comment by voima-eetu** [comment]
I overcame the issue by removing Rock Ridge support when making the ISO. (So mkisofs -command without '-rock' -flag)

**Comment by bo0tzz** [comment]
@Ramblurr did you ever find a solution to this issue on Proxmox?

**Comment by Ramblurr** [comment]
No, not yet. @dweomer said in the rancher slack that he will look into it when he has time. I've put my project on the backburner for now.

**Comment by philipsparrow** [comment]
I have been experiencing very similar panics from `metadata` in K3OS. After changing my ISO builder command from:
`genisoimage -input-charset utf-8 -output cdrom.iso config`
to
`genisoimage -input-charset utf-8  -joliet -rock -volid 'MYVOLUMENAME' -publisher 'My publisher' -iso-level 2 -output cdrom.iso config`
It seems to be working now. The frustrating problem was that it depended on the contents of my file `config`. Changes inside the file suggested an issue but the problem didn't just occur when the file got larger, larger files sometimes worked better. Perhaps it has something to do with trying block sizes or perhaps ISO padding.

My comment may not help in this case, but I hope it may be useful to someone researching the same issue.

**Comment by voima-eetu** [comment]
I have noticed that like @philipsparrow said, file size matters. Actually 2048 bytes is the limit. If config/metadata/cloud-init file is bigger than 2048 bytes linuxkit `metadata` command will result in 

> panic: runtime error: index out of range [0] with length 0

Actually 2048 bytes is the size of one volume descriptor in ISO9660 format.
I haven't tested yet if https://github.com/linuxkit/linuxkit/pull/3280 would fix the issue.

**Comment by mraerino** [comment]
oh, i encountered this, but didn't see this issue. it was fixed in go-diskfs in the meantime:
- https://github.com/diskfs/go-diskfs/pull/106
- https://github.com/diskfs/go-diskfs/pull/107

could someone update `go-diskfs` in linuxkit so this panic is gone for proxmox hosts?

**Comment by deitch** [comment]
Just needs a PR to update it to latest. Submit one and I can approve it and merge it in.

**Comment by mraerino** [comment]
any clue on what vendoring is used? i tried `trash` when updating the version but it didn't work for me. afaik there is not go mod present so i'm quite unsure about how to vendor the dependency properly

**Comment by deitch** [comment]
It is go modules. Just look inside `src/cmd/linuxkit/`

**Comment by mraerino** [comment]
oh i thought the metadata service was living at `pkg/metadata`?
with this module config? https://github.com/linuxkit/linuxkit/blob/master/pkg/metadata/vendor.conf

**Comment by deitch** [comment]
You're right. I mixed up the packages. That stuff uses vndr. But we wouldn't object to it being migrated to go modules. 😁

**Comment by mraerino** [comment]
i'll try what i can do

**Comment by mraerino** [comment]
did the thing: https://github.com/linuxkit/linuxkit/pull/3618

**Comment by voima-eetu** [comment]
@mraerino @deitch Any recomendations how/when could I get this to work?

**Comment by mraerino** [comment]
I think this needs to land first: https://github.com/linuxkit/linuxkit/pull/3627

**Comment by reitermarkus** [comment]
Any update on this? I also just encountered this, also with k3OS on Proxmox.
